CurrencyService.WebApi/Models/BackgroundWorker/BackgroundWorkerConfigurationViewModel.cs
using CurrencyService.BackgroundService.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CurrencyService.WebApi.Models.BackgroundWorker
{
    public class BackgroundWorkerConfigurationViewModel : IBackgroundWorkerConfiguration
    {
        public int SecondsInterval { get; set; }
    }
}

CurrencyService.WebApi/Models/BackgroundWorker/SaveConfigResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CurrencyService.WebApi.Models.BackgroundWorker
{
    public class SaveConfigResult
    {
        public bool Successfull { get; set; }

        public string Message { get; set; }
    }
}

CurrencyService.WebApi/Controllers/BackgroundWorkerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using FileSysIO = System.IO.File;
using System.Threading.Tasks;
using CurrencyService.WebApi.Models.BackgroundWorker;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceHelper;
using Newtonsoft.Json;
using CurrencyService.BackgroundService.Common;
using System.Diagnostics;
using CurrencyService.DAL;

namespace CurrencyService.WebApi.Controllers
{
    [Route("[controller]/[Action]")]
    [Authorize]
    public class BackgroundWorkerController : Controller
    {
        private readonly string _backgroundServicePathFolder;
        private const string _bgServiceName = "CurrencyService.BackgroundService";
        private readonly DbWriteService _dbWriteService; 
        public BackgroundWorkerController(DbWriteService dbWriteService) {
            _backgroundServicePathFolder = Path.GetDirectoryName(Finder.GetServicePath(_bgServiceName));
            _dbWriteService = dbWriteService;
        }
        public IActionResult Index()
        {
            return View(new BackgroundWorkerConfigurationViewModel());
        }

        [HttpPost]
        public IActionResult SaveConfig(BackgroundWorkerConfigurationViewModel model) {

            var result = new SaveConfigResult();

            try
            {
                _dbWriteService.AddBgWorkerConfiguration(model);
                result.Successfull = true;
            }
            catch(Exception e)
            {
                result.Successfull = false;
                result.Message = e.Message;
            }
                   
                
                
            
            return View(result);
        }

        
    }
}

CurrencyService.WebApi/Views/BackgroundWorker/Index.cshtml
@using CurrencyService.WebApi.Models.BackgroundWorker
@model BackgroundWorkerConfigurationViewModel
@{
    ViewData["Title"] = "Background Worker Configuration";
}

<form name="BackgroundWorkerConfiguration" method="post" action="@Url.Action("SaveConfig","BackgroundWorker")">
    <p>
        <b>Set bgworker data receival interval:</b><br>
        <input type="number" name="SecondsInterval" />
    </p>
    <p>
        <input type="submit" value="Отправить">
        <input type="reset" value="Очистить">
    </p>
</form>

CurrencyService.WebApi/Views/BackgroundWorker/SaveConfig.cshtml
@using CurrencyService.WebApi.Models.BackgroundWorker

@model SaveConfigResult


@{
    ViewData["Title"] = "SaveConfig";
}

<h1>
    Save config result:
    @if (Model.Successfull)
    {
        <text>Successfull</text> 
    }
    else
    {
        <text>NOOOOOOOOO : @Model.Message</text>
    }
</h1>